

import type { Metadata } from "next";

import "./index.css";



export const metadata: Metadata = {
  title: "bhanuka99x",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {children}
      </body>
    </html>
  );
}
