

import type { Metadata } from "next";

import "../styles/index.css";
import Header from "../components/Header";



export const metadata: Metadata = {
  title: "bhanuka99x",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">
        <Header />
        {children}
      </body>
    </html>
  );
}
